const express = require('express')
const router = express.Router()
const User = require('../models/User')
const Event = require('../models/Event')
const { authMiddleware } = require('../utils/jwt')
const { sendMail } = require('../utils/mailer')
const fetch = (...args) => globalThis.fetch(...args)

async function reverseGeocode(lat, lng){
  if(process.env.GEOCODE_PROVIDER === 'google' && process.env.GOOGLE_GEOCODE_API_KEY){
    const url = `https://maps.googleapis.com/maps/api/geocode/json?latlng=${lat},${lng}&key=${process.env.GOOGLE_GEOCODE_API_KEY}`
    const r = await fetch(url).then(r=>r.json())
    return r.results && r.results[0] ? r.results[0].formatted_address : null
  }
  // fallback to OSM Nominatim
  const url = `https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${lat}&lon=${lng}`
  const r = await fetch(url).then(r=>r.json())
  return r.display_name || null
}

async function handleHelp(req, res) {
  const { lat, lng, alertText } = req.body || {}
  const user = await User.findById(req.user.id)
  const contacts = user.contacts || []
  const location = lat && lng ? await reverseGeocode(lat, lng) : null
  const locationName = location?.fullAddress || 'Unknown location'
  const subject = '🚨 Emergency Alert - Immediate Attention Required'
  const time = new Date().toLocaleString()
  const body = `Dear Emergency Contact,\n\nThis is an automated emergency alert generated by the Accident Guardian System.\n\nVictim Name:\n${user.name || user.email}\n\nPhone Number:\n${user.phone || ''}\n\nTime:\n${time}\n\nCurrent Location:\n${locationName}\n\nLatitude & Longitude:\n${lat}, ${lng}\n\nGoogle Maps Link:\nhttps://maps.google.com/?q=${lat},${lng}\n\nWarning:\nA potential accident or emergency situation has been detected. Please try contacting the individual immediately and provide assistance if required.\n\nThis message was automatically generated by the Accident Guardian System.`

  for (const c of contacts) {
    try { await sendMail({ to: c.email, subject, text: body }) } catch (e) { console.error('email error', e) }
  }

  await Event.create({ user: user._id, type: 'HELP_TRIGGERED', payload: { lat, lng, locationName, city: location?.city, state: location?.state, country: location?.country, alertText } })
  res.json({ ok:true })
}

router.post('/', authMiddleware, handleHelp)
router.post('/help', authMiddleware, handleHelp)

module.exports = router
