const { reverseGeocode } = require('./geocode')
const { sendMail } = require('./mailer')

function buildSubject() {
  return '🚨 Emergency Alert - Immediate Attention Required'
}

function buildBody(user, location, alertText) {
  const timestamp = new Date().toLocaleString()
  return `Dear Emergency Contact,\n\nThis is an automated emergency alert generated by the Accident Guardian System.\n\nVictim Name:\n${user.name || user.email}\n\nPhone Number:\n${user.phone || ''}\n\nTime:\n${timestamp}\n\nCurrent Location:\n${location.fullAddress || 'Unknown address'}\n\nLatitude & Longitude:\n${location.lat}, ${location.lng}\n\nGoogle Maps Link:\n${location.mapsUrl}\n\nWarning:\nA potential accident or emergency situation has been detected. Please try contacting the individual immediately and provide assistance if required.\n\nThis message was automatically generated by the Accident Guardian System.`
}

async function triggerEmergency(user, contacts, lat, lng, alertText) {
  const location = await reverseGeocode(lat, lng)
  const payload = {
    type: alertText || 'Accident Alert',
    user: {
      id: user._id,
      name: user.name || user.email,
      phone: user.phone || ''
    },
    location: {
      lat,
      lng,
      fullAddress: location?.fullAddress || `${lat}, ${lng}`,
      city: location?.city || '',
      state: location?.state || '',
      country: location?.country || '',
      mapsUrl: location?.mapsUrl || `https://maps.google.com/?q=${lat},${lng}`
    },
    alertText: alertText || 'Emergency detected',
    timestamp: new Date().toISOString()
  }

  const subject = buildSubject()
  const body = buildBody(user, payload.location, alertText)

  for (const contact of contacts) {
    if (!contact || !contact.email) continue
    try {
      await sendMail({
        to: contact.email,
        subject,
        text: body
      })
    } catch (err) {
      console.error('Emergency email failed for', contact.email, err)
    }
  }

  return payload
}

module.exports = { triggerEmergency }
